apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: mc-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mc-server
  minReplicas: 1
  maxReplicas: 1   # Minecraft は 1Pod固定
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 200
