apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ include "mc.fullname" . }}-players'
data:
  ops.txt: |
    {{- range .Values.players.ops }}
    {{ . }}
    {{- end }}

  whitelist.txt: |
    {{- range .Values.players.whitelist.users }}
    {{ . }}
    {{- end }}
