apiVersion: v1
kind: Service
metadata:
  name: {{ include "mc.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "mc.name" . }}
  ports:
    - name: minecraft
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}