apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: mc-config
    behavior: replace
    literals:
      - TYPE=paper
      - VERSION=1.21.1
      - MEMORY=2G
      - EULA=true
      - LOG_FORMAT=plain
      - S3_SYNC_ENABLED=true
      - S3_PREFIX=paper-lobby
