apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

configMapGenerator:
  - name: mc-config
    behavior: replace
    literals:
      - TYPE=fabric
      - VERSION=latest
      - MEMORY=4G
      - EULA=true
      - LOG_FORMAT=plain
      - S3_SYNC_ENABLED=true
      - S3_PREFIX=fabric-snapshot
