apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# このオーバーレイで mc-config を上書きする
configMapGenerator:
  - name: mc-config
    behavior: replace
    literals:
      - TYPE=fabric
      - VERSION=1.21.11
      - MEMORY=6G
      - EULA=true
      - LOG_FORMAT=plain
      - S3_SYNC_ENABLED=true
      - S3_PREFIX=fabric-smp
