apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: minecraft-servers
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/YOUR_NAME/YOUR_REPO.git
        revision: main
        directories:
          - path: deploy/k8s/servers/*
  template:
    metadata:
      name: mc-{{path.basename}}
    spec:
      project: default
      source:
        repoURL: https://github.com/YOUR_NAME/YOUR_REPO.git
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: mc-{{path.basename}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
